vagrant_subnet = ENV["VAGRANT_SUBNET"] || "192.168.100"

Vagrant.configure("2") do |config|
  config.omnibus.chef_version = :latest

  config.vm.box = "opscode-centos-6.5"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"

  config.vm.hostname = "nodejs"
  config.vm.network "private_network", ip: "#{vagrant_subnet}.100"

  config.vm.synced_folder "../..", "/Development"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--cpus", "2",
    ]
  end

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      "nodejs" => {
        "install_method" => "source"
      }
    }
    chef.run_list = [
      "recipe[nodejs-devenv]"
    ]
  end
end
